# Each route describes how an incoming URL will be processedby Platform.sh.

"https://{default}/":
    type: upstream
    upstream: "ll_project:http"
"https://www.{default}/":
    type: redirect
    to: "https://{default}/"